### PR TITLE
chore: dropped fileclient in its entirety as there is now a mostly fully featured API

### PR DESCRIPTION
**Pull request by madhuravius**
local tests still should test if the provider can be built and terratest.

for ensuring terratest function - we can probably just validate in a rapid plan check in the test suite (without running an apply) to make sure our terratest tests are fine so we don't have to wait for full end to end flows that could take 30+ mins

### CODE REVIEW

**Comment by mdelaossa** [comment]
I love seeing PRs that delete stuff but - what's going to happen with tests here? You still have REMOTE_TESTING panic, so what are the leftover tests testing?

**Comment by madhuravius** [comment]
>  You still have REMOTE_TESTING panic, so what are the leftover tests testing?

There is no actual e2e testing strategy but that will get dumped when we use it. When we have a clear E2E strategy that's remote we can enable it.  There are still local tests enabled (happy path) to ensure our terraform compiles/does basic things before we enable some remote tests (both on the terraform resource_test.go's and on terratest).

Right now we'd have to set that manually to run it on our locals.

**Comment by aguilinger** [comment]
I think you overeagerly dropped [tests/redis/redis_test.go](https://github.com/aptible/terraform-provider-aptible-v2/pull/37/files#diff-6f4f3698a130f5a5ae93300b204cfcf033386cf67d2414097bb20bb12784a8f2)

**Comment by madhuravius** [comment]
> I think you overeagerly dropped [tests/redis/redis_test.go](https://github.com/aptible/terraform-provider-aptible-v2/pull/37/files#diff-6f4f3698a130f5a5ae93300b204cfcf033386cf67d2414097bb20bb12784a8f2)

definitely did, local showed it as untracked files and i think it would've appeared as zero-diff, sorry and thanks for the catch, should be reverted now

**Review by mdelaossa — APPROVED** [review]
LGTM now that you reverted the redis test deletion

**Pull request merged**
